 hello i am excited to learn pytorch


In [ ]:
!nvidia-smi

Wed Jun 26 13:15:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##00-pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


### introduction to Tensors

### Creating tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
#Tensor and dimensions
TENSOR = torch.tensor([[[1,2,3],[3,7,8],[1,6,7],[3,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 7, 8],
         [1, 6, 7],
         [3, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 3])

###Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
Start with random numbers -> look at data -> update random numbers -> update random numbers

In [ ]:
# Create a random tensors of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8465, 0.9035, 0.8104, 0.8323],
        [0.7563, 0.8688, 0.9952, 0.6334],
        [0.9482, 0.0500, 0.3972, 0.6608]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) #height, width, color channels RGB
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_tensor

tensor([[[0.2721, 0.8435, 0.4483],
         [0.9309, 0.0944, 0.6218],
         [0.0745, 0.7038, 0.7025],
         ...,
         [0.0517, 0.6986, 0.8998],
         [0.3176, 0.5286, 0.7098],
         [0.8747, 0.5819, 0.1160]],

        [[0.4696, 0.3982, 0.8579],
         [0.2008, 0.4237, 0.9264],
         [0.9524, 0.9032, 0.6944],
         ...,
         [0.4551, 0.4504, 0.6558],
         [0.8340, 0.5574, 0.3509],
         [0.1968, 0.4763, 0.3188]],

        [[0.7821, 0.8762, 0.7749],
         [0.2455, 0.3378, 0.7268],
         [0.2752, 0.5694, 0.6703],
         ...,
         [0.2973, 0.5946, 0.3426],
         [0.4807, 0.2841, 0.0493],
         [0.9885, 0.3323, 0.8190]],

        ...,

        [[0.7664, 0.2085, 0.7321],
         [0.5704, 0.5151, 0.0188],
         [0.3344, 0.3886, 0.5544],
         ...,
         [0.9987, 0.4057, 0.7458],
         [0.6919, 0.9597, 0.2192],
         [0.2204, 0.4998, 0.4880]],

        [[0.9067, 0.1103, 0.4637],
         [0.4646, 0.2638, 0.5673],
         [0.

###Zeros and ones

In [ ]:
#Create the tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensor-like

In [ ]:
#use torch.range()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32